### ISSUE TITLE
timezone vs timezone(s)

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/go-whosonfirst-timezones#1]
Heya

Checking out this code today I noticed the module name is plural `module github.com/whosonfirst/go-whosonfirst-timezones` but the repo name is singular `https://github.com/whosonfirst/go-whosonfirst-timezone`.

Copy->pasting the URL from an `import` statement results in a 404 😢

**Comment by thisisaaronland** [comment]
Fixed, thanks.
